####
##
## Konnected Garage Door Opener (GDOv1-S)
## Firmware configuration for ESPHome
##
## filename: garage-door-GDOv1-S.yaml
## GitHub: https://github.com/konnected-io/konnected-esphome
## Buy Konnected hardware: https://konnected.io
## Help & Support: https://help@konnected.io (support is provided for purchasers of Konnected hardware)
##
## Copyright© 2023 Konnected Inc.
##
## Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation 
## files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, 
## modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software
## is furnished to do so, subject to the following conditions:
##
## The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
##
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
## OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE 
## LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR 
## IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
##
####

####
# INTRODUCTION
# 
# This ESPHome based firmware configuration is designed for the Konnected Garage Door Opener v1,
# but can also run on any ESP8266 device. The Garage Door Opener retrofits an older style traditional
# garage door opener and has the following features which are included as packages below:
#
# 1. Wired contact sensor for detecting open/closed state of garage door
# 2. Optical range sensor for detecting open/closed state of garage door
# 3. Emulates a garage door opener button wired to a dry contact relay to open/close the garage door.
# 4. Adds a Garage Door "Cover" entity that is exposed to Home Assistant. The cover entity incorporates the state of the 
#    garage door and controls to open/close/stop it.
# 5. Flashes an onboard LED and beeps an onboard piezo sounder as a warning before automatically closing.


####
# GENERAL SETTINGS
# Customize these variables to your preferences and needs
# more: https://esphome.io/guides/configuration-types.html#substitutions
substitutions:

  ####
  # NAME
  # By default, the name of the ESPHome device is "konnected-xxxxxx" where xxxxxx is a unique identifier. The device's
  # hostname on your network is also defined by the name, defaulting to "konnected-xxxxxx.local". Edit this variable to
  # customize the name and hostname. Note: only lowercase characters, numbers and hyphen(-) are allowed.
  name: konnected
  friendly_name: Garage Door Opener
  project_name: konnected.garage-door-gdov1-s
  project_version: "1.2.4"
  garage_door_cover_name: Garage Door
  switch_name: Switch
  warning_beep_name: Warning Beep

  ####
  # GARAGE DOOR OPENER MOMENTARY DURATION
  # Duration to make the relay contact closure for the garage door opener button circuit. 
  garage_door_opener_momentary_duration: 300ms

  ####
  # OPEN GARAGE DOOR DISTANCE MARGIN OF ERROR
  # The margin of error (+/-) in meters from the value above to consider the garage door in the open position.
  open_garage_door_distance_margin_of_error: "0.1"

  ####
  # GARAGE DOOR CLOSE WARNING DURATION
  # Duration to blink the warning LED and beep the buzzer before the garage door closes.
  garage_door_close_warning_duration: 5s

  ####
  # ADDITIONAL SETTTINGS
  warning_beep_pulse_time: 100ms
  warning_beep_pause_time: 130ms
  sensor_debounce_time: 200ms
  range_sensor_polling_time: 2500ms
  range_sensor_debounce_time: 3s
  blink_on_state: "true"

  ####
  # INTERNAL MAPPINGS
  # DO NOT EDIT THESE when using Konnected hardware
  door_control_pin: D5
  wired_sensor_pin: D9
  warning_beep_pin: D8
  warning_leds_pin: D7
  output_switch_pin: D6
  status_led: D4
  sda: GPIO4
  scl: GPIO5

packages:

  remote_package:
    url: https://github.com/konnected-io/konnected-esphome
    ref: master
    refresh: 5min
    files:
      ####
      # CORE
      # This package is required
      - packages/core-esp8266.yaml

      ####
      # GARAGE DOOR WIRED SENSOR
      # Enables a wired contact sensor for reporting the open or closed state of the garage door
      # via the physical INPUT terminals.
      - packages/garage-door-wired-sensor.yaml

      ####
      # GARAGE DOOR RANGE SENSOR
      # Enables the optical laser range sensor included with some Konnected Garage Door opener models to detect
      # the open/closed state of an overhead garage door.
      - packages/vl53l0x-range-sensor.yaml

      ####
      # GARAGE DOOR COVER
      # The Garage Door Cover is the main user interface entity representing a garage door in Home Assistant.
      # more: https://www.home-assistant.io/integrations/cover/
      # CHOOSE ONE of the following cover packages depending on the sensors used to determine the open/closed state of the door.
      #
      # 1. RANGE SENSOR ONLY - Include this line and remove or comment out the garage_door_input package below.
      - packages/garage-door-cover-range.yaml
      #
      # 2. WIRED SENSOR ONLY - Include this line and remove or comment out the vl53l0x_range_sensor package below.
      # - packages/garage-door-cover-wired.yaml
      #
      # 3. WIRED & RANGE SENSORS - Include this line.
      # - packages/garage-door-cover-wired-and-range.yaml

      ####
      # GARAGE DOOR OPENER BUTTON
      # Enables the garage door opener relay labeled DOOR on the Konnected Garage Door Opener as a button entity. When
      # pressed, the relay will close the dry contact, simulating a physical press of the garage door opener wall button.
      - packages/garage-door-opener-button.yaml

      ####
      # SWITCH
      # Enables 12V switched output labeled STR on the Konnected Garage Door opener as a switch entity
      - packages/switch.yaml

      ####
      # WARNING LED
      # Enables the onboard warning LED light, with strobe effect. Used to visually warn of garage door automatic closing.
      - packages/warning-led.yaml

      ####
      # PRE-CLOSE WARNING
      # Enables a repeating beep using the onboard piezo buzzer. Used to audibly warn of a garage door automatic closing.
      # Requires the 'warning-beep.yaml' package.
      - packages/pre-close-warning.yaml

      ####
      # WIFI
      - packages/wifi.yaml

      ####
      # MDNS
      # Enables the _konnected MDNS/zeroconf service advertisement needed for the Konnected App
      - packages/mdns.yaml

      ####
      # STATUS LED
      # Enables the onboard blue status LED as an activity/error indicator
      - packages/status-led.yaml

      ####
      # WARNING BEEP
      # Enables a 'Warning Beep' entity, intended to be used with a piezo buzzer or other pulsing.
      # binary output This is implemented using the light component with strobe effect to create a 
      # repeated beeping sound or pulsing action that can be turned on via the _strobe_ effect.
      - packages/warning-beep.yaml

####
# DASHBOARD IMPORT
# Enables automatic discovery and upgrades via ESPHome Dashboard
# more: https://esphome.io/guides/getting_started_hassio.html
dashboard_import:
  package_import_url: github://konnected-io/konnected-esphome/garage-door-GDOv1-S.yaml@master
  import_full_config: false

####
# WEB SEVER
# Enables the built-in web server for viewing the device state, internals and controls via web browser
# on the same local network as the device.
web_server:
  include_internal: true

#### 
# LOGGER
# more: https://esphome.io/components/logger.html
logger:

####
# NATIVE API for HOME ASSISTANT
# Enables the native API for Home Assistant
# more: https://esphome.io/components/api.html
api:
