####
##
## Konnected Garage Door Opener blaQ (GDOv2-Q)
## Firmware configuration for ESPHome
##
## filename: garage-door-esp32.yaml
## GitHub: https://github.com/konnected-io/konnected-esphome
## Buy Konnected hardware: https://konnected.io
## Help & Support: https://help@konnected.io (support is provided for purchasers of Konnected hardware)
##
## Copyright© 2023 Konnected Inc.
##
## Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation
## files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy,
## modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software
## is furnished to do so, subject to the following conditions:
##
## The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
##
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
## OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
## LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR
## IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
##
####

####
# INTRODUCTION
#
# This ESPHome based firmware configuration is designed for the Konnected Garage Door Opener GDOv2-S which is built on the ESP32-S3-MINI.
# The Garage Door Opener retrofits an older style traditional garage door opener with a dry-contact trigger and has the
# following features which are included as packages below:
#
# 1. Wired contact sensor for detecting open/closed state of garage door
# 2. Optical range sensor for detecting open/closed state of garage door
# 3. Emulates a garage door opener button wired to a dry contact relay to open/close the garage door.
# 4. Adds a Garage Door "Cover" entity that is exposed to Home Assistant. The cover entity incorporates the state of the
#    garage door and controls to open/close/stop it.
# 5. Flashes an onboard LED and beeps an onboard piezo sounder as a warning before automatically closing.

####
# GENERAL SETTINGS
# Customize these variables to your preferences and needs
# more: https://esphome.io/guides/configuration-types.html#substitutions

####
# GENERAL SETTINGS
# Customize these variables to your preferences and needs
# more: https://esphome.io/guides/configuration-types.html#substitutions
substitutions:

  ####
  # NAME
  # By default, the name of the ESPHome device is "konnected-xxxxxx" where xxxxxx is a unique identifier. The device's
  # hostname on your network is also defined by the name, defaulting to "konnected-xxxxxx.local". Edit this variable to
  # customize the name and hostname. Note: only lowercase characters, numbers and hyphen(-) are allowed.
  name: konnected
  friendly_name: GDO blaQ
  project_name: konnected.garage-door-gdov2-q
  project_version: "1.5.2"
  garage_door_cover_name: Garage Door
  garage_light_name: Garage Light
  garage_openings_name: Garage Openings
  garage_lock_name: Lock
  garage_motion_name: Motion
  garage_obstruction_name: Obstruction
  garage_motor_name: Motor
  garage_button_name: Wall Button
  garage_sync_name: Synced


  ####
  # GARAGE DOOR CLOSE WARNING DURATION
  # Duration to blink the warning LED and beep the buzzer before the garage door closes.
  garage_door_close_warning_duration: 5s

  ####
  # ADDITIONAL SETTTINGS
  sensor_debounce_time: 200ms
  blink_on_state: "true"

  ####
  # INTERNAL MAPPINGS
  # DO NOT EDIT these when using Konnected hardware
  uart_tx_pin: GPIO1
  uart_rx_pin: GPIO2
  warning_beep_pin: GPIO4
  warning_leds_pin: GPIO3
  status_led: GPIO18
  input1: GPIO5
  input2: GPIO9

external_components:
  - source: github://konnected-io/konnected-esphome@master
    components: [ secplus_gdo ]

  # Un-comment below and comment above for local modification
  # - source:
  #     type: local
  #     path: components
  #   components: [ secplus_gdo ]

####
# PACKAGES
# Each package includes a Garage Door Opener feature described
# Remove or comment out any packages that you do not need or want.
packages:

  remote_package:
    url: https://github.com/konnected-io/konnected-esphome
    ref: master
    refresh: 5min
    files:

      ####
      # CORE
      # This package is required and sets up core ESPHome features.
      - packages/core-esp32-s3.yaml

      ####
      # WIFI
      # Enables WiFi connectivity and diagnostics. Uncommet below to enable WiFi.
      # wifi: !include packages/wifi.yaml
      - packages/wifi-esp32.yaml

      ####
      # MDNS
      # Enables the _konnected MDNS/zeroconf service advertisement needed for the Konnected App
      - packages/mdns.yaml

      ####
      # WARNING LED
      # Enables the onboard warning LED light, with strobe effect. Used to visually warn of garage door automatic closing.
      # warning_led: !include packages/warning-led.yaml
      - packages/warning-led.yaml

      ####
      # PRE-CLOSE WARNING
      # Enables a pleasant and customizable pre-close warning tone  using the onboard piezo buzzer. Used to audibly
      # warn of a garage door automatic closing.
      - packages/buzzer-rtttl.yaml
      - packages/pre-close-warning-tones.yaml

      ####
      # STATUS LED
      # Enables the onboard blue status LED as an activity/error indicator
      # status_led: !include packages/status-led.yaml
      - packages/status-led.yaml

      ####
      # SECPLUS GDO
      # The logic and capabilities of the GDO communication
      - packages/secplus-gdo.yaml
      - packages/debug.yaml

####
# DASHBOARD IMPORT
# Enables automatic discovery and upgrades via ESPHome Dashboard
# more: https://esphome.io/guides/getting_started_hassio.html
dashboard_import:
  package_import_url: github://konnected-io/konnected-esphome/garage-door-GDOv2-Q.yaml@master
  import_full_config: false

####
# LOGGER
# more: https://esphome.io/components/logger.html
logger:
  level: DEBUG
  # hardware_uart: UART0 # -- uncomment on batch 2403; not needed on batch 2404 and newer
  logs:
    # esp-idf: VERBOSE
    # api: VERBOSE
    api.service: DEBUG
    esp32_ble: DEBUG
    esp32_ble_server: DEBUG
    scheduler: DEBUG
    esp32.preferences: DEBUG
    sensor.filter: DEBUG
    rtttl: DEBUG
    cover: DEBUG
    sensor: DEBUG
    ledc.output: INFO
    json: INFO

####
# NATIVE API
# Enables the native ESPHome API
# more: https://esphome.io/components/api.html
api:

web_server:

esphome:
  platformio_options:
    lib_deps:
      - https://github.com/konnected-io/gdolib#943c516
    build_flags:
      - -Wl,--wrap=esp_panic_handler