substitutions:
  # Override to "true" in device config if alarm2 pin is a strapping pin with a safe pull-down.
  alarm2_ignore_strapping_warning: "false"

switch:
  - id: alarm2
    name: Alarm 2
    platform: gpio
    icon: mdi:bullhorn
    pin:
      number: $alarm2
      ignore_strapping_warning: ${alarm2_ignore_strapping_warning}
