binary_sensor:

  - id: zone11
    name: Zone 11   
    pin:
      number: $zone11
      mode: INPUT
    platform: gpio   
    filters:
      - delayed_on_off: $sensor_debounce_time
    on_state:
      - if:
          condition:
            lambda: return id(blink_on_state);
          then:
            - script.execute: blink_status_led
