binary_sensor:

  - id: zone12
    name: Zone 12
    pin:
      number: $zone12
      mode: INPUT
    platform: gpio   
    filters:
      - delayed_on_off: $sensor_debounce_time
    on_state:
      - if:
          condition:
            lambda: return id(blink_on_state);
          then:
            - script.execute: blink_status_led
