binary_sensor:

  - id: zone3
    name: Zone 3    
    pin:
      number: $zone3
      mode: INPUT_PULLUP
    platform: gpio   
    filters:
      - delayed_on_off: $sensor_debounce_time
    on_state:
      then:
        - light.turn_on: blue_status_led
        - delay: 100ms
        - light.turn_off: blue_status_led
