substitutions:
  ethernet_type: RTL8201

packages:
  alarm_panel_pro_esp32: !include ../alarm-panel-pro-esp32-1.yaml
  ethernet: !include ../packages/ethernet.yaml

esphome:
  name_add_mac_suffix: true

