esphome:
  name: $name
  friendly_name: $friendly_name
  name_add_mac_suffix: true
  project:
    name: $project_name
    version: $project_version 
  on_boot:
    then:
      - text_sensor.template.publish:
          id: device_id
          state: !lambda 'return get_mac_address();'

esp32:  
  board: wesp32
  framework:
    type: esp-idf
    version: recommended

substitutions:
  status_led_inverted: "false"

# overrides the MDNS component to add a Konnected service
external_components:
  - source: github://konnected-io/konnected-esphome@master
    components: [ mdns ]

text_sensor:
  - platform: template
    name: Device ID
    id: device_id
    entity_category: diagnostic
    update_interval: never
    
sensor:
  - platform: uptime
    name: Uptime
    entity_category: diagnostic

button:
  - platform: restart
    name: Restart
    entity_category: config
  # - platform: factory_reset
  #   name: Factory Reset
  #   entity_category: config