substitutions:
  transition_timeout: 60s

cover:
  - platform: template
    name: $garage_door_cover_name
    id: garage_door
    device_class: garage

    # Opens the garage door only if the garage door is currently closed
    open_action:
      - if:
          condition:
            lambda: return id(garage_door).position == COVER_CLOSED;
          then:
            - button.press: garage_door_opener_button
            - cover.template.publish:
                id: garage_door
                current_operation: OPENING
            - script.execute: garage_door_transition_timeout
          else:
            - script.execute: error_tone_1
            - lambda: ESP_LOGW("konnected.gdov2-s","Garage door is already open. Ignoring open action.");

    
    # Closes the garage door only if the garage door is currently open.
    # Triggers the pre-close warning before closing
    close_action:
      - if:
          condition:
            lambda: return id(garage_door).position == COVER_OPEN;
          then:
            - button.press: pre_close_warning
            - delay: $garage_door_close_warning_duration
            - button.press: garage_door_opener_button
            - cover.template.publish:
                id: garage_door
                current_operation: CLOSING
            - script.execute: garage_door_transition_timeout
          else:
            - script.execute: error_tone_1
            - lambda: ESP_LOGW("konnected.gdov2-s","Garage door is already closed. Ignoring close action.");
    
    # Toggles the garage door open or closed
    # If the action would cause the door to close, then the pre-close warning is
    # triggered prior to closing
    toggle_action:
      - if:
          condition:
            lambda: return id(garage_door).position == COVER_OPEN;
          then:
            - button.press: pre_close_warning
            - delay: $garage_door_close_warning_duration
            - cover.template.publish:
                id: garage_door
                current_operation: CLOSING
            - script.execute: garage_door_transition_timeout
          else:
            - cover.template.publish:
                id: garage_door
                current_operation: OPENING
            - script.execute: garage_door_transition_timeout
      - button.press: garage_door_opener_button
    
    # Triggers the garage door button to stop only if the garage door is known to be moving
    stop_action:
      - if:
          condition:
            not:
              lambda: return id(garage_door).current_operation == CoverOperation::COVER_OPERATION_IDLE;
          then:
            - button.press: garage_door_opener_button
            - cover.template.publish:
                id: garage_door
                current_operation: IDLE

script:
  - id: garage_door_transition_timeout
    mode: restart
    then:
      - delay: $transition_timeout 
      - if:
          condition:
            lambda: return id(garage_door).current_operation == COVER_OPERATION_OPENING ||
                           id(garage_door).current_operation == COVER_OPERATION_CLOSING;
          then:
            - lambda: ESP_LOGW("konnected.gdov2-s","Garage door transition timed out. Resetting state.");
            - cover.template.publish:
                id: garage_door
                current_operation: IDLE
