<<: !include garage-door-cover.yaml

binary_sensor:
  - id: !extend garage_door_input
    on_state:
      - if:
          condition:
            lambda: return x;
          then:
            - cover.template.publish:
                id: garage_door
                state: OPEN
                current_operation: IDLE
          else:
            - cover.template.publish:
                id: garage_door
                state: CLOSED
                current_operation: IDLE
