globals:
  - id: gdo_err_margin
    type: float
    restore_value: true
    initial_value: $open_garage_door_distance_margin_of_error

i2c:
  sda: $sda
  scl: $scl
  scan: True

number:
  - platform: template
    name: $friendly_name Sensor calibration
    id: open_garage_door_distance_from_ceiling
    icon: mdi:ruler
    entity_category: config
    unit_of_measurement: m
    device_class: distance
    step: 0.01
    max_value: 2.0
    min_value: 0.1
    optimistic: true
    restore_value: true

sensor:
  - platform: vl53l0x
    name: $friendly_name Sensor distance
    update_interval: $range_sensor_polling_time
    long_range: true
    accuracy_decimals: 2
    id: range_sensor
    entity_category: diagnostic
    
api:
  services:
    - service: calibrate_open_garage
      then:
        - number.set:
            id: open_garage_door_distance_from_ceiling
            value: !lambda return id(range_sensor).state;

binary_sensor:
  - platform: template
    id: garage_door_range_sensor
    internal: true
    lambda: |-
      float calibrated_distance = id(open_garage_door_distance_from_ceiling).state;
      if (std::isnan(id(range_sensor).state) || id(range_sensor).state > calibrated_distance + id(gdo_err_margin)) {
        return false;
      } else if (id(range_sensor).state < 0 + id(gdo_err_margin)) {
        return false;
      } else if (id(range_sensor).state > calibrated_distance - id(gdo_err_margin)){
        return true;
      } else {
        return {};
      }
    filters:
      delayed_off: $range_sensor_debounce_time